import classnames from 'classnames';
import './common.scss';
import './security.scss';
import Button from "../../components/Button";

export default function () {
  return (
    <div className="security-setting-container">
      <div className="setting-title">Security</div>
      <div className="setting-desc">The security settings of your wallet</div>
      <div>
        <div className="secutity-card">
          <div className="security-title">Password</div>
          <div className="security-desc">change your wallet login password</div>
          <Button>Update Password</Button>
        </div>
        <div className="security-line" />
        <div className="secutity-card">
          <div className="security-title">Recovery Phrases</div>
          <div className="security-desc warning">
            A recovery phrase grants full access to all wallets generated by it.
            You can manage and export your recovery phrases.
          </div>
          <Button state={'danger'}>I understand, show my phrases</Button>
        </div>
        <div className="security-line" />
        <div className="secutity-card">
          <div className="security-title">Private Key</div>
          <div className="security-desc warning">
            The private key grants full access to the current wallet. You can
            export the wallet by exporting its private key.
          </div>
          <Button state={'danger'} >I understand, show my private key</Button>

        </div>
      </div>
    </div>
  );
}
