import React from 'react';
import { View } from 'react-native';
import { StackScreenProps } from '@react-navigation/stack';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { RootStackParamList } from '@/../App';
import { Gray_100, Gray_400 } from '@/styles/colors';
import Typography from '@/components/Typography';
import { Button } from '@/components/Button';
import Toast from 'react-native-toast-message';

export const Security: React.FC<StackScreenProps<RootStackParamList, 'Security'>> = ({ navigation, route }) => {
  const { top, bottom } = useSafeAreaInsets();

  return (
    <View style={{ flexDirection: 'column', flexGrow: 1, backgroundColor: 'white' }}>
      <View
        style={{
          flexDirection: 'column',
          justifyContent: 'center',
          // alignItems: 'center',
          gap: 32,
          paddingHorizontal: 24,
        }}
      >
        <View style={{ marginVertical: 4, gap: 8 }}>
          <Typography.Headline children="Security" color="black" />
          <Typography.Body children="Check the security settings." color={Gray_400} />
        </View>

        <View style={{ flexDirection: 'column', gap: 8 }}>
          <Typography.Subtitle children="Recovery Phrases" />
          <Typography.Body
            children="A recovery phrase grants full access to all wallets generated by it. You can manage and export your recovery phrases."
            color={Gray_400}
          />
          <View />

          <Button
            onPress={() => {
              navigation.navigate('SecurityWarning', { next: 'Phrase' });
            }}
            type="Error"
            title="Show the Phrases"
          />
        </View>

        <View style={{ flexDirection: 'column', gap: 8 }}>
          <Typography.Subtitle children="Private Key" />
          <Typography.Body
            children="The private key grants full access to the current wallet. You can export the wallet by exporting its private key."
            color={Gray_400}
          />
          <View />

          <Button
            onPress={() => {
              // navigation.navigate('SecurityWarning', { next: 'PrivateKey' });
              Toast.show({
                type: 'info',
                text1: `This feature is WIP`,
                visibilityTime: 3000,
              });
            }}
            type="Error"
            title="Show the Private Key"
          />
        </View>
      </View>
      <View style={{ height: bottom }} />
    </View>
  );
};
